# run.yaml
apiVersion: v1
kind: Pod
metadata:
  name: run
spec:
  containers:
  - name: run-container
    image: debian
    command: ["bin/bash"]
    args: ["-c", "echo ${SECRET_ENV} ; cat /etc/secret/secret"]
    env:
    - name: SECRET_ENV #
      valueFrom:
        secretKeyRef:
          name: topsecret #
          key: secretenv #
    volumeMounts:
    - name: secretdir
      mountPath: "/etc/secret" #
  volumes:
  - name: secretdir
    secret:
      secretName: topsecret
      items:
      - key: secretfile
        path: secret
