apiVersion: v1
kind: Pod
metadata:
  labels:
    name: secretstest1
  name: secretstest
spec:
  volumes:
    - name: "secretstest"
      secret:
        secretName: mysecret
  containers:
    - image: nginx:1.7.1
      name: awebserver
      volumeMounts:
        - mountPath: "/tmp/mysec"
          name: "secretstest"
