apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    app: web
spec:
  containers:
    - name: centos6
      image: centos:centos6
      command: ["sleep", "3600"]
    - name: centos7
      image: centos:centos7
      command: ["sleep", "3600"]
  nodeSelector:
    kubernetes.io/hostname: node2.rmohan.com 
