apiVersion: v1
kind: Pod
metadata:
  name: use-secret
spec:
  containers:
  - name: mycontainer
    image: centos
    command: [ "/bin/sh", "-c", "while true; do sleep 3; done" ]
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
