apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.1.70
    - 192.168.1.72
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
