apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]
