apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["sleep", "3600"]

