apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: example-container
      image: busybox
      # exec Keep it sleeping for operation by exec later
      command: ["sleep", "3600"]
      # ConfigMap Mount the ConfigMap
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # ConfigMap ConfigMap Specifies the name of the resource (the name obtained by kubectl get configmap)
        name: test-config
